// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
// All rights reserved.
// Use of this source code is governed by BSD 3-Clause license that can
// be found in the LICENSE file.
//
// GENERATED FILE — do not edit by hand. Re-run `dart run ffigen` to
// regenerate after updating libsmb2 headers.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for libsmb2. Generated by `dart run ffigen`.
/// Do not edit by hand.
///
class LibSmb2Bindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibSmb2Bindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibSmb2Bindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Create an SMB2 context. Function returns NULL : Failed to create a
  /// context. *smb2 : A pointer to an smb2 context.
  ffi.Pointer<smb2_context> smb2_init_context() {
    return _smb2_init_context();
  }

  late final _smb2_init_contextPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<smb2_context> Function()>>(
          'smb2_init_context');
  late final _smb2_init_context =
      _smb2_init_contextPtr.asFunction<ffi.Pointer<smb2_context> Function()>();

  /// Close an SMB2 context
  void smb2_close_context(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_close_context(
      smb2,
    );
  }

  late final _smb2_close_contextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<smb2_context>)>>(
          'smb2_close_context');
  late final _smb2_close_context = _smb2_close_contextPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>)>();

  /// Destroy an smb2 context.
  void smb2_destroy_context(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_destroy_context(
      smb2,
    );
  }

  late final _smb2_destroy_contextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<smb2_context>)>>(
          'smb2_destroy_context');
  late final _smb2_destroy_context = _smb2_destroy_contextPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>)>();

  /// EVENT SYSTEM INTEGRATION ======================== The following functions
  /// are used to integrate libsmb2 in an event system.
  int smb2_get_fd(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_get_fd(
      smb2,
    );
  }

  late final _smb2_get_fdPtr =
      _lookup<ffi.NativeFunction<t_socket Function(ffi.Pointer<smb2_context>)>>(
          'smb2_get_fd');
  late final _smb2_get_fd =
      _smb2_get_fdPtr.asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// Returns which events that we need to poll for for the smb2 file
  /// descriptor.
  int smb2_which_events(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_which_events(
      smb2,
    );
  }

  late final _smb2_which_eventsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<smb2_context>)>>(
          'smb2_which_events');
  late final _smb2_which_events = _smb2_which_eventsPtr
      .asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// Called to process the events when events become available for the smb2
  /// file descriptor.
  int smb2_service(
    ffi.Pointer<smb2_context> smb2,
    int revents,
  ) {
    return _smb2_service(
      smb2,
      revents,
    );
  }

  late final _smb2_servicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<smb2_context>, ffi.Int)>>('smb2_service');
  late final _smb2_service = _smb2_servicePtr
      .asFunction<int Function(ffi.Pointer<smb2_context>, int)>();

  /// Set the timeout in seconds after which a command will be aborted with
  /// SMB2_STATUS_IO_TIMEOUT. If you use timeouts with the async API you must
  /// make sure to call smb2_service() at least once every second.
  void smb2_set_timeout(
    ffi.Pointer<smb2_context> smb2,
    int seconds,
  ) {
    return _smb2_set_timeout(
      smb2,
      seconds,
    );
  }

  late final _smb2_set_timeoutPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<smb2_context>, ffi.Int)>>('smb2_set_timeout');
  late final _smb2_set_timeout = _smb2_set_timeoutPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>, int)>();

  void smb2_set_version(
    ffi.Pointer<smb2_context> smb2,
    smb2_negotiate_version version,
  ) {
    return _smb2_set_version(
      smb2,
      version.value,
    );
  }

  late final _smb2_set_versionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<smb2_context>, ffi.UnsignedInt)>>('smb2_set_version');
  late final _smb2_set_version = _smb2_set_versionPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>, int)>();

  /// Gets the libsmb2 version being linked while used. This function will be
  /// available on 5.x
  void smb2_get_libsmb2Version(
    ffi.Pointer<smb2_libversion> smb2_ver,
  ) {
    return _smb2_get_libsmb2Version(
      smb2_ver,
    );
  }

  late final _smb2_get_libsmb2VersionPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<smb2_libversion>)>>(
      'smb2_get_libsmb2Version');
  late final _smb2_get_libsmb2Version = _smb2_get_libsmb2VersionPtr
      .asFunction<void Function(ffi.Pointer<smb2_libversion>)>();

  /// gets the (currently) negotiated dialect
  int smb2_get_dialect(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_get_dialect(
      smb2,
    );
  }

  late final _smb2_get_dialectPtr = _lookup<
          ffi.NativeFunction<ffi.Uint16 Function(ffi.Pointer<smb2_context>)>>(
      'smb2_get_dialect');
  late final _smb2_get_dialect = _smb2_get_dialectPtr
      .asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// Set the security mode for the connection. This is a combination of the
  /// flags SMB2_NEGOTIATE_SIGNING_ENABLED and SMB2_NEGOTIATE_SIGNING_REQUIRED
  /// Default is 0.
  void smb2_set_security_mode(
    ffi.Pointer<smb2_context> smb2,
    int security_mode,
  ) {
    return _smb2_set_security_mode(
      smb2,
      security_mode,
    );
  }

  late final _smb2_set_security_modePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Uint16)>>('smb2_set_security_mode');
  late final _smb2_set_security_mode = _smb2_set_security_modePtr
      .asFunction<void Function(ffi.Pointer<smb2_context>, int)>();

  /// Set whether smb3 encryption should be used or not.
  void smb2_set_seal(
    ffi.Pointer<smb2_context> smb2,
    int val,
  ) {
    return _smb2_set_seal(
      smb2,
      val,
    );
  }

  late final _smb2_set_sealPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<smb2_context>, ffi.Int)>>('smb2_set_seal');
  late final _smb2_set_seal = _smb2_set_sealPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>, int)>();

  /// Set whether smb2 signing should be required or not 0 : do not require
  /// signing. This is the default. !0 : require signing.
  void smb2_set_sign(
    ffi.Pointer<smb2_context> smb2,
    int val,
  ) {
    return _smb2_set_sign(
      smb2,
      val,
    );
  }

  late final _smb2_set_signPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<smb2_context>, ffi.Int)>>('smb2_set_sign');
  late final _smb2_set_sign = _smb2_set_signPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>, int)>();

  /// Set authentication method. SMB2_SEC_UNDEFINED (use KRB if available or
  /// NTLM if not) SMB2_SEC_NTLMSSP SMB2_SEC_KRB5
  void smb2_set_authentication(
    ffi.Pointer<smb2_context> smb2,
    int val,
  ) {
    return _smb2_set_authentication(
      smb2,
      val,
    );
  }

  late final _smb2_set_authenticationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<smb2_context>, ffi.Int)>>('smb2_set_authentication');
  late final _smb2_set_authentication = _smb2_set_authenticationPtr
      .asFunction<void Function(ffi.Pointer<smb2_context>, int)>();

  /// Set the username that we will try to authenticate as. Default is to try to
  /// authenticate as the current user.
  void smb2_set_user(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> user,
  ) {
    return _smb2_set_user(
      smb2,
      user,
    );
  }

  late final _smb2_set_userPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>)>>('smb2_set_user');
  late final _smb2_set_user = _smb2_set_userPtr.asFunction<
      void Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Set the password that we will try to authenticate as. This function is
  /// only needed when libsmb2 is built --without-libkrb5
  void smb2_set_password(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _smb2_set_password(
      smb2,
      password,
    );
  }

  late final _smb2_set_passwordPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>)>>('smb2_set_password');
  late final _smb2_set_password = _smb2_set_passwordPtr.asFunction<
      void Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Set the domain when authenticating. This function is only needed when
  /// libsmb2 is built --without-libkrb5
  void smb2_set_domain(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> domain,
  ) {
    return _smb2_set_domain(
      smb2,
      domain,
    );
  }

  late final _smb2_set_domainPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>)>>('smb2_set_domain');
  late final _smb2_set_domain = _smb2_set_domainPtr.asFunction<
      void Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Set the workstation when authenticating. This function is only needed when
  /// libsmb2 is built --without-libkrb5
  void smb2_set_workstation(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> workstation,
  ) {
    return _smb2_set_workstation(
      smb2,
      workstation,
    );
  }

  late final _smb2_set_workstationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>)>>('smb2_set_workstation');
  late final _smb2_set_workstation = _smb2_set_workstationPtr.asFunction<
      void Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Sync call to connect to a share. On unix, if user is NULL then default to
  /// the current user.
  int smb2_connect_share(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> server,
    ffi.Pointer<ffi.Char> share,
    ffi.Pointer<ffi.Char> user,
  ) {
    return _smb2_connect_share(
      smb2,
      server,
      share,
      user,
    );
  }

  late final _smb2_connect_sharePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('smb2_connect_share');
  late final _smb2_connect_share = _smb2_connect_sharePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Sync call to disconnect from a share/
  int smb2_disconnect_share(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_disconnect_share(
      smb2,
    );
  }

  late final _smb2_disconnect_sharePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<smb2_context>)>>(
          'smb2_disconnect_share');
  late final _smb2_disconnect_share = _smb2_disconnect_sharePtr
      .asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// This function returns a description of the last encountered error.
  ffi.Pointer<ffi.Char> smb2_get_error(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_get_error(
      smb2,
    );
  }

  late final _smb2_get_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<smb2_context>)>>('smb2_get_error');
  late final _smb2_get_error = _smb2_get_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<smb2_context>)>();

  int smb2_get_nterror(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_get_nterror(
      smb2,
    );
  }

  late final _smb2_get_nterrorPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<smb2_context>)>>(
          'smb2_get_nterror');
  late final _smb2_get_nterror = _smb2_get_nterrorPtr
      .asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// Convert an smb2/nt error code into an errno value
  int nterror_to_errno(
    int status,
  ) {
    return _nterror_to_errno(
      status,
    );
  }

  late final _nterror_to_errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Uint32)>>(
          'nterror_to_errno');
  late final _nterror_to_errno =
      _nterror_to_errnoPtr.asFunction<int Function(int)>();

  /// Sync opendir()
  ffi.Pointer<smb2dir> smb2_opendir(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _smb2_opendir(
      smb2,
      path,
    );
  }

  late final _smb2_opendirPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<smb2dir> Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>)>>('smb2_opendir');
  late final _smb2_opendir = _smb2_opendirPtr.asFunction<
      ffi.Pointer<smb2dir> Function(
          ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// closedir()
  void smb2_closedir(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2dir> smb2dir$1,
  ) {
    return _smb2_closedir(
      smb2,
      smb2dir$1,
    );
  }

  late final _smb2_closedirPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<smb2dir>)>>('smb2_closedir');
  late final _smb2_closedir = _smb2_closedirPtr.asFunction<
      void Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2dir>)>();

  /// readdir()
  ffi.Pointer<smb2dirent> smb2_readdir(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2dir> smb2dir$1,
  ) {
    return _smb2_readdir(
      smb2,
      smb2dir$1,
    );
  }

  late final _smb2_readdirPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<smb2dirent> Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<smb2dir>)>>('smb2_readdir');
  late final _smb2_readdir = _smb2_readdirPtr.asFunction<
      ffi.Pointer<smb2dirent> Function(
          ffi.Pointer<smb2_context>, ffi.Pointer<smb2dir>)>();

  /// Sync open()
  ffi.Pointer<smb2fh> smb2_open(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
    int flags,
  ) {
    return _smb2_open(
      smb2,
      path,
      flags,
    );
  }

  late final _smb2_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<smb2fh> Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>, ffi.Int)>>('smb2_open');
  late final _smb2_open = _smb2_openPtr.asFunction<
      ffi.Pointer<smb2fh> Function(
          ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>, int)>();

  /// Sync close()
  int smb2_close(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
  ) {
    return _smb2_close(
      smb2,
      fh,
    );
  }

  late final _smb2_closePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>)>>('smb2_close');
  late final _smb2_close = _smb2_closePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>)>();

  /// Sync fsync()
  int smb2_fsync(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
  ) {
    return _smb2_fsync(
      smb2,
      fh,
    );
  }

  late final _smb2_fsyncPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>)>>('smb2_fsync');
  late final _smb2_fsync = _smb2_fsyncPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>)>();

  /// GetMaxReadWriteSize SMB2 servers have a maximum size for read/write data
  /// that they support.
  int smb2_get_max_read_size(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_get_max_read_size(
      smb2,
    );
  }

  late final _smb2_get_max_read_sizePtr = _lookup<
          ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<smb2_context>)>>(
      'smb2_get_max_read_size');
  late final _smb2_get_max_read_size = _smb2_get_max_read_sizePtr
      .asFunction<int Function(ffi.Pointer<smb2_context>)>();

  int smb2_get_max_write_size(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_get_max_write_size(
      smb2,
    );
  }

  late final _smb2_get_max_write_sizePtr = _lookup<
          ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<smb2_context>)>>(
      'smb2_get_max_write_size');
  late final _smb2_get_max_write_size = _smb2_get_max_write_sizePtr
      .asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// Sync pread() Use smb2_get_max_read_size to discover the maximum data size
  /// that the server supports.
  int smb2_pread(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
    ffi.Pointer<ffi.Uint8> buf,
    int count,
    int offset,
  ) {
    return _smb2_pread(
      smb2,
      fh,
      buf,
      count,
      offset,
    );
  }

  late final _smb2_preadPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
              ffi.Pointer<ffi.Uint8>, ffi.Uint32, ffi.Uint64)>>('smb2_pread');
  late final _smb2_pread = _smb2_preadPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
          ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Sync pwrite() Use smb2_get_max_write_size to discover the maximum data
  /// size that the server supports.
  int smb2_pwrite(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
    ffi.Pointer<ffi.Uint8> buf,
    int count,
    int offset,
  ) {
    return _smb2_pwrite(
      smb2,
      fh,
      buf,
      count,
      offset,
    );
  }

  late final _smb2_pwritePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
              ffi.Pointer<ffi.Uint8>, ffi.Uint32, ffi.Uint64)>>('smb2_pwrite');
  late final _smb2_pwrite = _smb2_pwritePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
          ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Sync read()
  int smb2_read(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
    ffi.Pointer<ffi.Uint8> buf,
    int count,
  ) {
    return _smb2_read(
      smb2,
      fh,
      buf,
      count,
    );
  }

  late final _smb2_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
              ffi.Pointer<ffi.Uint8>, ffi.Uint32)>>('smb2_read');
  late final _smb2_read = _smb2_readPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
          ffi.Pointer<ffi.Uint8>, int)>();

  /// Sync write()
  int smb2_write(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
    ffi.Pointer<ffi.Uint8> buf,
    int count,
  ) {
    return _smb2_write(
      smb2,
      fh,
      buf,
      count,
    );
  }

  late final _smb2_writePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
              ffi.Pointer<ffi.Uint8>, ffi.Uint32)>>('smb2_write');
  late final _smb2_write = _smb2_writePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
          ffi.Pointer<ffi.Uint8>, int)>();

  /// Sync unlink()
  int smb2_unlink(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _smb2_unlink(
      smb2,
      path,
    );
  }

  late final _smb2_unlinkPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Char>)>>('smb2_unlink');
  late final _smb2_unlink = _smb2_unlinkPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Sync rmdir()
  int smb2_rmdir(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _smb2_rmdir(
      smb2,
      path,
    );
  }

  late final _smb2_rmdirPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>>('smb2_rmdir');
  late final _smb2_rmdir = _smb2_rmdirPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Sync mkdir()
  int smb2_mkdir(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _smb2_mkdir(
      smb2,
      path,
    );
  }

  late final _smb2_mkdirPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>>('smb2_mkdir');
  late final _smb2_mkdir = _smb2_mkdirPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>)>();

  /// Sync statvfs()
  int smb2_statvfs(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<Smb2StatVfsNative> statvfs,
  ) {
    return _smb2_statvfs(
      smb2,
      path,
      statvfs,
    );
  }

  late final _smb2_statvfsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<Smb2StatVfsNative>)>>('smb2_statvfs');
  late final _smb2_statvfs = _smb2_statvfsPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<Smb2StatVfsNative>)>();

  /// Sync fstat()
  int smb2_fstat(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
    ffi.Pointer<smb2_stat_64> st,
  ) {
    return _smb2_fstat(
      smb2,
      fh,
      st,
    );
  }

  late final _smb2_fstatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
              ffi.Pointer<smb2_stat_64>)>>('smb2_fstat');
  late final _smb2_fstat = _smb2_fstatPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
          ffi.Pointer<smb2_stat_64>)>();

  /// Sync stat()
  int smb2_stat(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<smb2_stat_64> st,
  ) {
    return _smb2_stat(
      smb2,
      path,
      st,
    );
  }

  late final _smb2_statPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<smb2_stat_64>)>>('smb2_stat');
  late final _smb2_stat = _smb2_statPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<smb2_stat_64>)>();

  /// Sync rename()
  int smb2_rename(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> oldpath,
    ffi.Pointer<ffi.Char> newpath,
  ) {
    return _smb2_rename(
      smb2,
      oldpath,
      newpath,
    );
  }

  late final _smb2_renamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('smb2_rename');
  late final _smb2_rename = _smb2_renamePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Sync truncate() Function returns 0 : Success -errno : An error occurred.
  int smb2_truncate(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
    int length,
  ) {
    return _smb2_truncate(
      smb2,
      path,
      length,
    );
  }

  late final _smb2_truncatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
              ffi.Uint64)>>('smb2_truncate');
  late final _smb2_truncate = _smb2_truncatePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>, int)>();

  /// Sync ftruncate() Function returns 0 : Success -errno : An error occurred.
  int smb2_ftruncate(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<smb2fh> fh,
    int length,
  ) {
    return _smb2_ftruncate(
      smb2,
      fh,
      length,
    );
  }

  late final _smb2_ftruncatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>,
              ffi.Uint64)>>('smb2_ftruncate');
  late final _smb2_ftruncate = _smb2_ftruncatePtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<smb2fh>, int)>();

  /// Sync utimes() Function returns 0 : Success -errno : An error occurred.
  int smb2_utimes(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
    int atime_us,
    int mtime_us,
  ) {
    return _smb2_utimes(
      smb2,
      path,
      atime_us,
      mtime_us,
    );
  }

  late final _smb2_utimesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
              ffi.Uint64, ffi.Uint64)>>('smb2_utimes');
  late final _smb2_utimes = _smb2_utimesPtr.asFunction<
      int Function(
          ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>, int, int)>();

  /// Sync readlink()
  int smb2_readlink(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> buf,
    int bufsiz,
  ) {
    return _smb2_readlink(
      smb2,
      path,
      buf,
      bufsiz,
    );
  }

  late final _smb2_readlinkPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Uint32)>>('smb2_readlink');
  late final _smb2_readlink = _smb2_readlinkPtr.asFunction<
      int Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, int)>();

  /// Sync echo()
  int smb2_echo(
    ffi.Pointer<smb2_context> smb2,
  ) {
    return _smb2_echo(
      smb2,
    );
  }

  late final _smb2_echoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<smb2_context>)>>(
          'smb2_echo');
  late final _smb2_echo =
      _smb2_echoPtr.asFunction<int Function(ffi.Pointer<smb2_context>)>();

  /// Sync share_enum() This function only works when connected to the IPC$
  /// share.
  ffi.Pointer<srvsvc_NetrShareEnum_rep> smb2_share_enum_sync(
    ffi.Pointer<smb2_context> smb2,
    SHARE_INFO_enum level,
  ) {
    return _smb2_share_enum_sync(
      smb2,
      level.value,
    );
  }

  late final _smb2_share_enum_syncPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<srvsvc_NetrShareEnum_rep> Function(
              ffi.Pointer<smb2_context>,
              ffi.UnsignedInt)>>('smb2_share_enum_sync');
  late final _smb2_share_enum_sync = _smb2_share_enum_syncPtr.asFunction<
      ffi.Pointer<srvsvc_NetrShareEnum_rep> Function(
          ffi.Pointer<smb2_context>, int)>();

  /// Low level RAW SMB2 interface
  late final ffi.Pointer<ffi.Uint8> _compound_file_id =
      _lookup<ffi.Uint8>('compound_file_id');

  ffi.Pointer<ffi.Uint8> get compound_file_id => _compound_file_id;

  /// This function is used to free the data returned by the query functions.
  void smb2_free_data(
    ffi.Pointer<smb2_context> smb2,
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _smb2_free_data(
      smb2,
      ptr,
    );
  }

  late final _smb2_free_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<smb2_context>,
              ffi.Pointer<ffi.Void>)>>('smb2_free_data');
  late final _smb2_free_data = _smb2_free_dataPtr.asFunction<
      void Function(ffi.Pointer<smb2_context>, ffi.Pointer<ffi.Void>)>();
}

enum smb2_command {
  SMB2_NEGOTIATE(0),
  SMB2_SESSION_SETUP(1),
  SMB2_LOGOFF(2),
  SMB2_TREE_CONNECT(3),
  SMB2_TREE_DISCONNECT(4),
  SMB2_CREATE(5),
  SMB2_CLOSE(6),
  SMB2_FLUSH(7),
  SMB2_READ(8),
  SMB2_WRITE(9),
  SMB2_LOCK(10),
  SMB2_IOCTL(11),
  SMB2_CANCEL(12),
  SMB2_ECHO(13),
  SMB2_QUERY_DIRECTORY(14),
  SMB2_CHANGE_NOTIFY(15),
  SMB2_QUERY_INFO(16),
  SMB2_SET_INFO(17),
  SMB2_OPLOCK_BREAK(18),
  SMB1_NEGOTIATE(114);

  final int value;
  const smb2_command(this.value);

  static smb2_command fromValue(int value) => switch (value) {
        0 => SMB2_NEGOTIATE,
        1 => SMB2_SESSION_SETUP,
        2 => SMB2_LOGOFF,
        3 => SMB2_TREE_CONNECT,
        4 => SMB2_TREE_DISCONNECT,
        5 => SMB2_CREATE,
        6 => SMB2_CLOSE,
        7 => SMB2_FLUSH,
        8 => SMB2_READ,
        9 => SMB2_WRITE,
        10 => SMB2_LOCK,
        11 => SMB2_IOCTL,
        12 => SMB2_CANCEL,
        13 => SMB2_ECHO,
        14 => SMB2_QUERY_DIRECTORY,
        15 => SMB2_CHANGE_NOTIFY,
        16 => SMB2_QUERY_INFO,
        17 => SMB2_SET_INFO,
        18 => SMB2_OPLOCK_BREAK,
        114 => SMB1_NEGOTIATE,
        _ => throw ArgumentError('Unknown value for smb2_command: $value'),
      };
}

/// OPEN
final class smb2fh extends ffi.Opaque {}

/// This creates a new smb2fh based on fileid. Free it with smb2_close_async()
final class smb2_context extends ffi.Opaque {}

final class smb2_iovec extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> buf;

  @ffi.Size()
  external int len;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      free;
}

final class smb2_symlink_reparse_buffer extends ffi.Struct {
  @ffi.Uint32()
  external int flags;

  external ffi.Pointer<ffi.Char> subname;

  external ffi.Pointer<ffi.Char> printname;
}

final class smb2_oplock_break_notification extends ffi.Struct {
  @ffi.Uint8()
  external int oplock_level;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> file_id;
}

final class smb2_oplock_break_acknowledgement extends ffi.Struct {
  @ffi.Uint8()
  external int oplock_level;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> file_id;
}

final class smb2_oplock_break_reply extends ffi.Struct {
  @ffi.Uint8()
  external int oplock_level;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> file_id;
}

final class smb2_lease_break_notification extends ffi.Struct {
  @ffi.Uint16()
  external int new_epoch;

  @ffi.Uint32()
  external int flags;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> lease_key;

  @ffi.Uint32()
  external int current_lease_state;

  @ffi.Uint32()
  external int new_lease_state;

  @ffi.Uint32()
  external int break_reason;

  @ffi.Uint32()
  external int access_mask_hint;

  @ffi.Uint32()
  external int share_mask_hint;
}

final class smb2_lease_break_acknowledgement extends ffi.Struct {
  @ffi.Uint32()
  external int flags;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> lease_key;

  @ffi.Uint32()
  external int lease_state;

  @ffi.Uint64()
  external int lease_duration;
}

final class smb2_lease_break_reply extends ffi.Struct {
  @ffi.Uint32()
  external int flags;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> lease_key;

  @ffi.Uint32()
  external int lease_state;

  @ffi.Uint64()
  external int lease_duration;
}

final class UnnamedUnion extends ffi.Union {
  external smb2_oplock_break_notification oplock;

  external smb2_oplock_break_reply oplockrep;

  external smb2_lease_break_notification lease;

  external smb2_lease_break_reply leaserep;
}

/// note that for oplocks, notifications (request) and responses (reply) come
/// from the server, while acknowledgements come from the client
final class smb2_oplock_or_lease_break_reply extends ffi.Struct {
  @ffi.Uint16()
  external int struct_size;

  @ffi.Int()
  external int break_type;

  external UnnamedUnion lock;
}

typedef smb2_command_cbFunction = ffi.Void Function(
    ffi.Pointer<smb2_context> smb2,
    ffi.Int status,
    ffi.Pointer<ffi.Void> command_data,
    ffi.Pointer<ffi.Void> cb_data);
typedef Dartsmb2_command_cbFunction = void Function(
    ffi.Pointer<smb2_context> smb2,
    int status,
    ffi.Pointer<ffi.Void> command_data,
    ffi.Pointer<ffi.Void> cb_data);

/// Generic callback for completion of smb2_*_async(). command_data depends on
/// status.
typedef smb2_command_cb
    = ffi.Pointer<ffi.NativeFunction<smb2_command_cbFunction>>;
typedef smb2_error_cbFunction = ffi.Void Function(
    ffi.Pointer<smb2_context> smb2, ffi.Pointer<ffi.Char> error_string);
typedef Dartsmb2_error_cbFunction = void Function(
    ffi.Pointer<smb2_context> smb2, ffi.Pointer<ffi.Char> error_string);

/// callback for getting error information when errors are set command_data
/// depends on status.
typedef smb2_error_cb = ffi.Pointer<ffi.NativeFunction<smb2_error_cbFunction>>;
typedef smb2_accepted_cbFunction = ffi.Int Function(
    ffi.Int fd, ffi.Pointer<ffi.Void> cb_data);
typedef Dartsmb2_accepted_cbFunction = int Function(
    int fd, ffi.Pointer<ffi.Void> cb_data);

/// callback for server accepting a new connection
typedef smb2_accepted_cb
    = ffi.Pointer<ffi.NativeFunction<smb2_accepted_cbFunction>>;
typedef smb2_client_connectionFunction = ffi.Void Function(
    ffi.Pointer<smb2_context> smb2, ffi.Pointer<ffi.Void> cb_data);
typedef Dartsmb2_client_connectionFunction = void Function(
    ffi.Pointer<smb2_context> smb2, ffi.Pointer<ffi.Void> cb_data);

/// callback when a new connection is made to setup context
typedef smb2_client_connection
    = ffi.Pointer<ffi.NativeFunction<smb2_client_connectionFunction>>;
typedef smb2_oplock_or_lease_break_cbFunction = ffi.Void Function(
    ffi.Pointer<smb2_context> smb2,
    ffi.Int status,
    ffi.Pointer<smb2_oplock_or_lease_break_reply> rep,
    ffi.Pointer<ffi.Uint8> new_oplock_level,
    ffi.Pointer<ffi.Uint32> new_lease_state);
typedef Dartsmb2_oplock_or_lease_break_cbFunction = void Function(
    ffi.Pointer<smb2_context> smb2,
    int status,
    ffi.Pointer<smb2_oplock_or_lease_break_reply> rep,
    ffi.Pointer<ffi.Uint8> new_oplock_level,
    ffi.Pointer<ffi.Uint32> new_lease_state);
typedef smb2_oplock_or_lease_break_cb
    = ffi.Pointer<ffi.NativeFunction<smb2_oplock_or_lease_break_cbFunction>>;

final class smb2_stat_64 extends ffi.Struct {
  @ffi.Uint32()
  external int smb2_type;

  @ffi.Uint32()
  external int smb2_nlink;

  @ffi.Uint64()
  external int smb2_ino;

  @ffi.Uint64()
  external int smb2_size;

  @ffi.Uint64()
  external int smb2_atime;

  @ffi.Uint64()
  external int smb2_atime_nsec;

  @ffi.Uint64()
  external int smb2_mtime;

  @ffi.Uint64()
  external int smb2_mtime_nsec;

  @ffi.Uint64()
  external int smb2_ctime;

  @ffi.Uint64()
  external int smb2_ctime_nsec;

  @ffi.Uint64()
  external int smb2_btime;

  @ffi.Uint64()
  external int smb2_btime_nsec;
}

final class Smb2StatVfsNative extends ffi.Struct {
  @ffi.Uint32()
  external int f_bsize;

  @ffi.Uint32()
  external int f_frsize;

  @ffi.Uint64()
  external int f_blocks;

  @ffi.Uint64()
  external int f_bfree;

  @ffi.Uint64()
  external int f_bavail;

  @ffi.Uint32()
  external int f_files;

  @ffi.Uint32()
  external int f_ffree;

  @ffi.Uint32()
  external int f_favail;

  @ffi.Uint32()
  external int f_fsid;

  @ffi.Uint32()
  external int f_flag;

  @ffi.Uint32()
  external int f_namemax;
}

final class smb2dirent extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  external smb2_stat_64 st;
}

typedef t_socket = ffi.Int;
typedef Dartt_socket = int;
typedef smb2_change_fd_cbFunction = ffi.Void Function(
    ffi.Pointer<smb2_context> smb2, t_socket fd, ffi.Int cmd);
typedef Dartsmb2_change_fd_cbFunction = void Function(
    ffi.Pointer<smb2_context> smb2, Dartt_socket fd, int cmd);
typedef smb2_change_fd_cb
    = ffi.Pointer<ffi.NativeFunction<smb2_change_fd_cbFunction>>;
typedef smb2_change_events_cbFunction = ffi.Void Function(
    ffi.Pointer<smb2_context> smb2, t_socket fd, ffi.Int events);
typedef Dartsmb2_change_events_cbFunction = void Function(
    ffi.Pointer<smb2_context> smb2, Dartt_socket fd, int events);
typedef smb2_change_events_cb
    = ffi.Pointer<ffi.NativeFunction<smb2_change_events_cbFunction>>;

/// Set which version of SMB to negotiate. Default is to let the server pick the
/// version.
enum smb2_negotiate_version {
  SMB2_VERSION_ANY(0),
  SMB2_VERSION_ANY2(2),
  SMB2_VERSION_ANY3(3),
  SMB2_VERSION_0202(514),
  SMB2_VERSION_0210(528),
  SMB2_VERSION_0300(768),
  SMB2_VERSION_0302(770),
  SMB2_VERSION_0311(785);

  final int value;
  const smb2_negotiate_version(this.value);

  static smb2_negotiate_version fromValue(int value) => switch (value) {
        0 => SMB2_VERSION_ANY,
        2 => SMB2_VERSION_ANY2,
        3 => SMB2_VERSION_ANY3,
        514 => SMB2_VERSION_0202,
        528 => SMB2_VERSION_0210,
        768 => SMB2_VERSION_0300,
        770 => SMB2_VERSION_0302,
        785 => SMB2_VERSION_0311,
        _ => throw ArgumentError(
            'Unknown value for smb2_negotiate_version: $value'),
      };
}

final class smb2_libversion extends ffi.Struct {
  @ffi.Uint8()
  external int major_version;

  @ffi.Uint8()
  external int minor_version;

  @ffi.Uint8()
  external int patch_version;
}

enum smb2_sec {
  SMB2_SEC_UNDEFINED(0),
  SMB2_SEC_NTLMSSP(1),
  SMB2_SEC_KRB5(2);

  final int value;
  const smb2_sec(this.value);

  static smb2_sec fromValue(int value) => switch (value) {
        0 => SMB2_SEC_UNDEFINED,
        1 => SMB2_SEC_NTLMSSP,
        2 => SMB2_SEC_KRB5,
        _ => throw ArgumentError('Unknown value for smb2_sec: $value'),
      };
}

/// OPENDIR
final class smb2dir extends ffi.Opaque {}

enum SHARE_INFO_enum {
  SHARE_INFO_0(0),
  SHARE_INFO_1(1),
  SHARE_INFO_2(2),
  SHARE_INFO_502(502);

  final int value;
  const SHARE_INFO_enum(this.value);

  static SHARE_INFO_enum fromValue(int value) => switch (value) {
        0 => SHARE_INFO_0,
        1 => SHARE_INFO_1,
        2 => SHARE_INFO_2,
        502 => SHARE_INFO_502,
        _ => throw ArgumentError('Unknown value for SHARE_INFO_enum: $value'),
      };
}

final class srvsvc_SHARE_INFO_0 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> netname;
}

final class srvsvc_SHARE_INFO_0_CONTAINER extends ffi.Struct {
  @ffi.Uint32()
  external int EntriesRead;

  external ffi.Pointer<srvsvc_SHARE_INFO_0> share_info_0;
}

final class srvsvc_SHARE_INFO_1 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> netname;

  @ffi.Uint32()
  external int type;

  external ffi.Pointer<ffi.Char> remark;
}

final class srvsvc_SHARE_INFO_1_CONTAINER extends ffi.Struct {
  @ffi.Uint32()
  external int EntriesRead;

  external ffi.Pointer<srvsvc_SHARE_INFO_1> share_info_1;
}

final class srvsvc_SHARE_INFO_2 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> netname;

  @ffi.Uint32()
  external int type;

  external ffi.Pointer<ffi.Char> remark;

  @ffi.Uint32()
  external int permissions;

  @ffi.Uint32()
  external int max_users;

  @ffi.Uint32()
  external int current_users;

  external ffi.Pointer<ffi.Char> path;

  external ffi.Pointer<ffi.Char> passwd;
}

final class srvsvc_SHARE_INFO_2_CONTAINER extends ffi.Struct {
  @ffi.Uint32()
  external int EntriesRead;

  external ffi.Pointer<srvsvc_SHARE_INFO_2> share_info_2;
}

/// Incomplete unless dcerpc/dcerpc-srvsvc.h (libdcerpc) is also included.
final class srvsvc_SHARE_INFO_502 extends ffi.Opaque {}

final class srvsvc_SHARE_INFO_502_CONTAINER extends ffi.Struct {
  @ffi.Uint32()
  external int EntriesRead;

  external ffi.Pointer<srvsvc_SHARE_INFO_502> share_info_502;
}

final class srvsvc_SHARE_ENUM_UNION extends ffi.Union {
  external srvsvc_SHARE_INFO_0_CONTAINER Level0;

  external srvsvc_SHARE_INFO_1_CONTAINER Level1;

  external srvsvc_SHARE_INFO_2_CONTAINER Level2;

  external srvsvc_SHARE_INFO_502_CONTAINER Level502;
}

final class srvsvc_SHARE_ENUM_STRUCT extends ffi.Struct {
  @ffi.Uint32()
  external int Level;

  external srvsvc_SHARE_ENUM_UNION ShareEnum;
}

final class srvsvc_NetrShareEnum_rep extends ffi.Struct {
  external srvsvc_SHARE_ENUM_STRUCT ses;

  @ffi.Uint32()
  external int total_entries;

  @ffi.Uint32()
  external int resume_handle;

  @ffi.Uint32()
  external int status;
}

const int SMB2_TYPE_FILE = 0;

const int SMB2_TYPE_DIRECTORY = 1;

const int SMB2_TYPE_LINK = 2;

const int LIBSMB2_MAJOR_VERSION = 4;

const int LIBSMB2_MINOR_VERSION = 0;

const int LIBSMB2_PATCH_VERSION = 0;

const int SRVSVC_SHARE_TYPE_DISKTREE = 0;

const int SRVSVC_SHARE_TYPE_PRINTQ = 1;

const int SRVSVC_SHARE_TYPE_DEVICE = 2;

const int SRVSVC_SHARE_TYPE_IPC = 3;

const int SRVSVC_SHARE_TYPE_TEMPORARY = 1073741824;

const int SRVSVC_SHARE_TYPE_HIDDEN = 2147483648;
