name: dart_smb2
description: Dart client for SMB2/3 built on libsmb2. Supports listing, reads, writes, streaming, caching, worker pool with reconnect and more. Targets macOS, Windows, Linux, iOS and Android.
version: 0.1.3
homepage: https://github.com/ales-drnz/dart_smb2
repository: https://github.com/ales-drnz/dart_smb2
issue_tracker: https://github.com/ales-drnz/dart_smb2/issues

topics:
  - cross-platform
  - smb2
  - smb3
  - samba
  - libsmb2


platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  ffi: ^2.1.0
  meta: ^1.15.0

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.25.6

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        pluginClass: DartSmb2Plugin
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        pluginClass: DartSmb2Plugin
        ffiPlugin: true
      windows:
        ffiPlugin: true
