// Copyright © 2026 & onwards, Alessandro Di Ronza <ales.drnz@gmail.com>.
// All rights reserved.
// Use of this source code is governed by BSD 3-Clause license that can be found in the LICENSE file.

/// Synchronous SMB2/3 client built directly on the ffigen-generated
/// libsmb2 bindings.
///
/// This is the single Dart layer above `lib/src/ffi/libsmb2_bindings.dart`
/// (purely generated by ffigen). It owns everything the public API needs
/// and the generated bindings don't provide: the `smb2_context*`
/// lifecycle, path NUL validation, error → typed exception classification,
/// POSIX open-flag dispatch, and chunked pwrite.
///
/// There is no intermediate C wrapper: this calls libsmb2 directly
/// through the generated bindings.
///
/// **Thread-safety caveat**: `smb2_init_context` / `smb2_destroy_context`
/// mutate a global `active_contexts` linked list in libsmb2's `init.c`
/// without internal locking, so concurrent calls from multiple isolates
/// can corrupt it. The mitigation is purely Dart-side ordering: every
/// worker spawn and close of every `Smb2Pool` (respawns of the
/// auto-reconnect included) and `Smb2Pool.listSharesOn` go through
/// `Smb2ContextLock`, one at a time per isolate. An `Smb2Client` used
/// directly from isolates of your own is unprotected unless its
/// `connect` / `listShares` / `disconnect` run through
/// `Smb2ContextLock.run` as well.
library;

import 'dart:ffi';
import 'dart:io' show Platform;
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'ffi/libsmb2_bindings.dart';
import 'ffi/native_lib.dart';
import 'smb2_error_type.dart';
import 'smb2_exceptions.dart';
import 'smb2_types.dart';

/// Opaque handle to an open file on a [Smb2Client].
///
/// Returned by [Smb2Client.openFileHandle] / [Smb2Client.openFileWithSize]
/// / [Smb2Client.openFileHandleWrite] and passed back to the handle-based
/// read/write/close methods. The underlying native pointer is not exposed
/// — callers never need to import `dart:ffi`.
class Smb2Handle {
  final Pointer<smb2fh> _fh;
  const Smb2Handle._(this._fh);

  /// Whether this handle wraps a non-null native pointer.
  bool get isValid => _fh != nullptr;
}

/// SMB2/3 client powered by libsmb2 via Dart FFI.
///
/// All operations are **synchronous** — run this client inside a
/// [Dart Isolate](https://api.dart.dev/stable/dart-isolate/Isolate-class.html)
/// to keep the UI responsive.
///
/// ```dart
/// final client = Smb2Client.open();
/// client.connect(host: '192.168.1.1', share: 'Music', user: 'guest');
/// final entries = client.listDirectory('');
/// client.disconnect();
/// ```
class Smb2Client implements Finalizable {
  final DynamicLibrary _lib;
  final LibSmb2Bindings _native;
  Pointer<smb2_context> _ctx = nullptr;
  late final NativeFinalizer _finalizer;

  Smb2Client._(this._lib) : _native = LibSmb2Bindings(_lib) {
    // Last-resort safety net for a leaked client: free the libsmb2
    // context if the caller forgets to call `disconnect()`. The bound
    // function is `smb2_destroy_context` (signature: void(void*)) — it
    // closes the socket and releases internal allocations, but does NOT
    // send a wire-level logoff first. Explicit `disconnect()` is still
    // preferred so the server can reclaim the session immediately.
    _finalizer = NativeFinalizer(
      _lib.lookup<NativeFunction<Void Function(Pointer)>>(
        'smb2_destroy_context',
      ),
    );
  }

  /// Create a client. The native library is resolved automatically via
  /// the Flutter plugin mechanism — no path arguments to wire up.
  factory Smb2Client.open() => Smb2Client._(openLibSmb2());

  /// Whether this client is connected to a share.
  bool get isConnected => _ctx != nullptr;

  // ─── Share enumeration ───────────────────────────────────────────────────

  /// List available shares on a server.
  ///
  /// This does **not** require an existing connection — it connects to `IPC$`
  /// internally, enumerates shares, and disconnects.
  ///
  /// **Thread-safety caveat**: allocates its own libsmb2 context, so the
  /// `active_contexts` race described in the library docs applies. Call it
  /// once at startup rather than concurrently from many isolates.
  ///
  /// Returns a list of [Smb2ShareInfo] with name and type.
  List<Smb2ShareInfo> listShares({
    required String host,
    String? user,
    String? password,
    String? domain,
    int timeoutSeconds = 30,
  }) {
    final ctx = _native.smb2_init_context();
    if (ctx == nullptr) {
      throw const Smb2Exception(
        'Failed to create SMB2 context for share enumeration',
      );
    }

    try {
      _applyCredentials(
        _native,
        ctx,
        user: user,
        password: password,
        domain: domain,
        timeoutSeconds: timeoutSeconds,
      );

      // Connect to IPC$ (the named-pipe transport for SRVSVC). `user` is
      // passed through verbatim — libsmb2 treats an empty string as "guest".
      using((arena) {
        final pHost = host.toNativeUtf8(allocator: arena).cast<Char>();
        final pIpc = r'IPC$'.toNativeUtf8(allocator: arena).cast<Char>();
        final pUser = (user ?? '').toNativeUtf8(allocator: arena).cast<Char>();
        final rc = _native.smb2_connect_share(ctx, pHost, pIpc, pUser);
        if (rc < 0) throw _makeError(_native, ctx, 'Connect to IPC\$ failed');
      });

      try {
        // SHARE_INFO_1 is value 1 in libsmb2's header — pass the typed enum
        // so it survives any future re-ordering of values upstream.
        final rep =
            _native.smb2_share_enum_sync(ctx, SHARE_INFO_enum.SHARE_INFO_1);
        if (rep == nullptr) {
          throw _makeError(_native, ctx, 'Share enumeration failed');
        }

        try {
          // The reply tree is:
          //   rep.ses.ShareEnum.Level1.{EntriesRead, share_info_1}
          //   share_info_1 → array of SHARE_INFO_1
          // `ShareEnum` is a named union here, so there is no synthetic
          // `unnamed` hop, the container points straight at the array, and
          // `netname` is already a NUL-terminated UTF-8 string.
          final container = rep.ref.ses.ShareEnum.Level1;
          final count = container.EntriesRead;
          final infosBase = container.share_info_1;
          if (count == 0 || infosBase == nullptr) {
            return const <Smb2ShareInfo>[];
          }

          final results = <Smb2ShareInfo>[];
          for (var i = 0; i < count; i++) {
            final info = (infosBase + i).ref;
            final namePtr = info.netname;
            final name =
                namePtr == nullptr ? '' : namePtr.cast<Utf8>().toDartString();
            results.add(Smb2ShareInfo(name: name, type: info.type));
          }
          return results;
        } finally {
          // `smb2_free_data` recursively frees the entire response tree
          // (containers + carrays + utf16 string buffers) the DCE/RPC
          // decoder allocated.
          _native.smb2_free_data(ctx, rep.cast());
        }
      } finally {
        _native.smb2_disconnect_share(ctx);
      }
    } finally {
      _native.smb2_destroy_context(ctx);
    }
  }

  // ─── Connection ─────────────────────────────────────────────────────────

  /// Connect to an SMB share.
  ///
  /// Paths in subsequent calls are **relative to the share root**.
  /// Use `''` (empty string) to refer to the share root — not `/`.
  ///
  /// Throws [Smb2Exception] on failure.
  void connect({
    required String host,
    required String share,
    String? user,
    String? password,
    String? domain,
    int timeoutSeconds = 30,
    bool seal = false,
    bool signing = false,
    Smb2Version version = Smb2Version.any,
  }) {
    if (isConnected) disconnect();

    final ctx = _native.smb2_init_context();
    if (ctx == nullptr) {
      throw const Smb2Exception(
        'Failed to create SMB2 context',
      );
    }

    try {
      _applyCredentials(
        _native,
        ctx,
        user: user,
        password: password,
        domain: domain,
        timeoutSeconds: timeoutSeconds,
      );
      if (seal) _native.smb2_set_seal(ctx, 1);
      if (signing) _native.smb2_set_sign(ctx, 1);
      if (version.value != 0) {
        _native.smb2_set_version(
          ctx,
          smb2_negotiate_version.fromValue(version.value),
        );
      }

      using((arena) {
        final pHost = host.toNativeUtf8(allocator: arena).cast<Char>();
        final pShare = share.toNativeUtf8(allocator: arena).cast<Char>();
        final pUser = (user ?? '').toNativeUtf8(allocator: arena).cast<Char>();
        final rc = _native.smb2_connect_share(ctx, pHost, pShare, pUser);
        if (rc < 0) throw _makeError(_native, ctx, 'Connect failed');
      });
    } catch (_) {
      // Release the context so we don't leak libsmb2 internal allocations.
      _native.smb2_destroy_context(ctx);
      rethrow;
    }

    _ctx = ctx;
    _finalizer.attach(this, _ctx.cast(), detach: this);
  }

  /// Disconnect from the share and release all resources.
  ///
  /// Sends a wire-level logoff (`smb2_disconnect_share`) so the server can
  /// reclaim the session, then frees the local context.
  void disconnect() {
    if (_ctx == nullptr) return;
    _finalizer.detach(this);
    _native.smb2_disconnect_share(_ctx);
    _native.smb2_destroy_context(_ctx);
    _ctx = nullptr;
  }

  /// Send a keepalive echo to the server.
  ///
  /// Returns normally if the connection is healthy.
  /// Throws [Smb2Exception] if the server is unreachable or the
  /// connection has been lost.
  void echo() {
    _ensureConnected();
    if (_native.smb2_echo(_ctx) < 0) {
      throw _makeError(_native, _ctx, 'Echo failed');
    }
  }

  // ─── Directory listing ──────────────────────────────────────────────────

  /// List all entries in a directory.
  ///
  /// [path] is relative to the share root. Use `''` for the root directory.
  /// Returns entries with name, type, size, and timestamps — no additional
  /// per-entry round-trips required.
  ///
  /// Throws [Smb2Exception] if the directory cannot be opened.
  List<Smb2DirEntry> listDirectory(String path) {
    _ensureConnected();
    final dir = using((arena) {
      final d = _native.smb2_opendir(_ctx, _path(path, arena));
      if (d == nullptr) {
        throw _makeError(_native, _ctx, 'Failed to list directory');
      }
      return d;
    });

    try {
      final results = <Smb2DirEntry>[];
      while (true) {
        final ent = _native.smb2_readdir(_ctx, dir);
        if (ent == nullptr) break;
        // smb2_readdir returns a pointer into libsmb2-owned memory that is
        // recycled on the next call — copy what we need immediately.
        final name = ent.ref.name.cast<Utf8>().toDartString();
        if (name == '.' || name == '..') continue;
        results
            .add(Smb2DirEntry(name: name, stat: _statFromNative(ent.ref.st)));
      }
      return results;
    } finally {
      _native.smb2_closedir(_ctx, dir);
    }
  }

  // ─── File reading ───────────────────────────────────────────────────────

  /// Read [length] bytes from a file at [offset].
  ///
  /// Ideal for reading partial content without downloading the entire file.
  ///
  /// Throws [Smb2Exception] on read failure.
  Uint8List readFileRange(String path, {int offset = 0, required int length}) {
    _ensureConnected();
    final fh = using((arena) {
      final h = _native.smb2_open(_ctx, _path(path, arena), _flags.rdonly);
      if (h == nullptr) throw _makeError(_native, _ctx, 'Open failed');
      return h;
    });

    final buf = malloc<Uint8>(length);
    try {
      final n = _native.smb2_pread(_ctx, fh, buf, length, offset);
      if (n < 0) {
        malloc.free(buf);
        throw _makeError(_native, _ctx, 'Read failed');
      }
      // Zero-copy: Dart GC owns the native buffer via NativeFinalizer.
      return buf.asTypedList(n, finalizer: malloc.nativeFree);
    } finally {
      _native.smb2_close(_ctx, fh);
    }
  }

  /// Read an entire file into memory.
  ///
  /// Sizes the buffer with `fstat` on the open handle, then loops `pread`
  /// until EOF. For large files prefer [readFileRange] to read only the
  /// bytes you need.
  ///
  /// Throws [Smb2Exception] on failure.
  Uint8List readFile(String path) {
    _ensureConnected();
    final fh = using((arena) {
      final h = _native.smb2_open(_ctx, _path(path, arena), _flags.rdonly);
      if (h == nullptr) throw _makeError(_native, _ctx, 'Open failed');
      return h;
    });

    try {
      return using((arena) {
        // Size up-front via fstat on the handle we just opened — avoids a
        // second path-based round-trip (and its TOCTOU window).
        final st = arena<smb2_stat_64>();
        if (_native.smb2_fstat(_ctx, fh, st) < 0) {
          throw _makeError(_native, _ctx, 'Read file failed (fstat)');
        }
        final size = st.ref.smb2_size;
        final out = Uint8List(size);
        if (size == 0) return out;

        // libsmb2 internally splits at the negotiated MaxReadSize; we loop
        // until we've drained the file, reusing one 1 MiB scratch buffer.
        var offset = 0;
        const chunk = 1024 * 1024;
        final buf = malloc<Uint8>(chunk);
        try {
          while (offset < size) {
            final remaining = size - offset;
            final toRead = remaining < chunk ? remaining : chunk;
            final n = _native.smb2_pread(_ctx, fh, buf, toRead, offset);
            if (n < 0) throw _makeError(_native, _ctx, 'Read file failed');
            if (n == 0) break; // unexpected EOF — file shrunk mid-read
            out.setRange(offset, offset + n, buf.asTypedList(n));
            offset += n;
          }
        } finally {
          malloc.free(buf);
        }
        // Trim if the file shrunk between fstat and the pread loop.
        return offset == size ? out : Uint8List.sublistView(out, 0, offset);
      });
    } finally {
      _native.smb2_close(_ctx, fh);
    }
  }

  // ─── File info ──────────────────────────────────────────────────────────

  /// Get file or directory metadata without opening the file.
  ///
  /// Uses an SMB2 compound request internally (Create + QueryInfo + Close)
  /// so it completes in a single network round-trip.
  ///
  /// Throws [Smb2Exception] on failure.
  Smb2Stat stat(String path) {
    _ensureConnected();
    return using((arena) {
      final out = arena<smb2_stat_64>();
      if (_native.smb2_stat(_ctx, _path(path, arena), out) < 0) {
        throw _makeError(_native, _ctx, 'Stat failed');
      }
      return _statFromNative(out.ref);
    });
  }

  /// Get the size of a file in bytes without opening it.
  ///
  /// Throws [Smb2Exception] on failure.
  int fileSize(String path) {
    _ensureConnected();
    return using((arena) {
      final out = arena<smb2_stat_64>();
      if (_native.smb2_stat(_ctx, _path(path, arena), out) < 0) {
        throw _makeError(_native, _ctx, 'File size failed');
      }
      return out.ref.smb2_size;
    });
  }

  /// Get filesystem statistics (total/free space, block sizes).
  ///
  /// [path] can be any path on the share — typically `''` for the share root.
  ///
  /// Throws [Smb2Exception] on failure.
  Smb2StatVfs statvfs(String path) {
    _ensureConnected();
    return using((arena) {
      final out = arena<Smb2StatVfsNative>();
      if (_native.smb2_statvfs(_ctx, _path(path, arena), out) < 0) {
        throw _makeError(_native, _ctx, 'Statvfs failed');
      }
      final s = out.ref;
      return Smb2StatVfs(
        blockSize: s.f_bsize,
        fragmentSize: s.f_frsize,
        totalBlocks: s.f_blocks,
        freeBlocks: s.f_bfree,
        availableBlocks: s.f_bavail,
        maxNameLength: s.f_namemax,
      );
    });
  }

  /// Read the target path of a symbolic link.
  ///
  /// libsmb2's `smb2_readlink` returns 0 on success without reporting how
  /// many bytes it wrote, and internally uses `strncpy` which does NOT
  /// NUL-terminate when the target fills the buffer. We allocate
  /// `bufferSize + 1` zeroed bytes and tell libsmb2 it owns only
  /// `bufferSize`, so the trailing zero is a forced NUL terminator.
  ///
  /// Throws [Smb2Exception] on failure (e.g., path is not a symlink).
  String readlink(String path) {
    _ensureConnected();
    return using((arena) {
      final buf = arena<Uint8>(_readlinkBufferSize + 1);
      final rc = _native.smb2_readlink(
        _ctx,
        _path(path, arena),
        buf.cast(),
        _readlinkBufferSize,
      );
      if (rc < 0) throw _makeError(_native, _ctx, 'Readlink failed');
      return buf.cast<Utf8>().toDartString();
    });
  }

  /// Check whether a file or directory exists.
  ///
  /// Returns `true` if the path exists, `false` if it does not.
  /// Throws [Smb2Exception] on connection or permission errors.
  bool exists(String path) {
    _ensureConnected();
    try {
      stat(path);
      return true;
    } on Smb2Exception catch (e) {
      if (e.type == Smb2ErrorType.fileNotFound) return false;
      rethrow;
    }
  }

  // ─── File handles (open once, read many, close once) ─────────────────

  /// Open a file for reading and return a reusable handle.
  ///
  /// Use [readHandle] to read from the handle, then [closeHandle] when done.
  /// This avoids repeated open/close network round-trips when reading
  /// multiple ranges from the same file.
  ///
  /// Throws [Smb2Exception] if the file cannot be opened.
  Smb2Handle openFileHandle(String path) {
    _ensureConnected();
    return using((arena) {
      final fh = _native.smb2_open(_ctx, _path(path, arena), _flags.rdonly);
      if (fh == nullptr) throw _makeError(_native, _ctx, 'Open failed');
      return Smb2Handle._(fh);
    });
  }

  /// Open a file and get its size in one call.
  ///
  /// Saves a round-trip compared to calling [fileSize] + [openFileHandle]
  /// separately. Returns `(handle, fileSize)`.
  ///
  /// Throws [Smb2Exception] on failure.
  (Smb2Handle handle, int size) openFileWithSize(String path) {
    _ensureConnected();
    final fh = using((arena) {
      final h = _native.smb2_open(_ctx, _path(path, arena), _flags.rdonly);
      if (h == nullptr) throw _makeError(_native, _ctx, 'Open failed');
      return h;
    });
    return using((arena) {
      final st = arena<smb2_stat_64>();
      if (_native.smb2_fstat(_ctx, fh, st) < 0) {
        _native.smb2_close(_ctx, fh);
        throw _makeError(_native, _ctx, 'Open failed (fstat)');
      }
      return (Smb2Handle._(fh), st.ref.smb2_size);
    });
  }

  /// Read [length] bytes at [offset] from an open file handle.
  ///
  /// The handle must have been obtained from [openFileHandle] or
  /// [openFileWithSize].
  Uint8List readHandle(
    Smb2Handle handle, {
    int offset = 0,
    required int length,
  }) {
    _ensureConnected();
    final buf = malloc<Uint8>(length);
    final n = _native.smb2_pread(_ctx, handle._fh, buf, length, offset);
    if (n < 0) {
      malloc.free(buf);
      throw _makeError(_native, _ctx, 'Handle read failed');
    }
    return buf.asTypedList(n, finalizer: malloc.nativeFree);
  }

  /// Close a file handle opened with [openFileHandle] or [openFileWithSize].
  void closeHandle(Smb2Handle handle) {
    if (_ctx == nullptr || handle._fh == nullptr) return;
    _native.smb2_close(_ctx, handle._fh);
  }

  // ─── Streaming ──────────────────────────────────────────────────────

  /// Read a file in chunks without loading everything into RAM.
  ///
  /// Yields [Uint8List] chunks of up to [chunkSize] bytes.
  /// Uses a file handle internally — opens once, reads sequentially, closes.
  Iterable<Uint8List> readFileChunked(
    String path, {
    int chunkSize = 1024 * 1024,
  }) sync* {
    final (handle, size) = openFileWithSize(path);
    try {
      int offset = 0;
      while (offset < size) {
        final toRead = (size - offset).clamp(0, chunkSize);
        yield readHandle(handle, offset: offset, length: toRead);
        offset += toRead;
      }
    } finally {
      closeHandle(handle);
    }
  }

  // ─── File writing ───────────────────────────────────────────────────────

  /// Write [data] to a file at [offset], creating it if it doesn't exist.
  ///
  /// Ideal for writing partial content or appending to a file.
  ///
  /// Throws [Smb2Exception] on write failure.
  void writeFileRange(String path, Uint8List data, {int offset = 0}) {
    _ensureConnected();
    using((arena) {
      final fh = _native.smb2_open(
        _ctx,
        _path(path, arena),
        _flags.wronly | _flags.creat,
      );
      if (fh == nullptr) {
        throw _makeError(_native, _ctx, 'Open for write failed');
      }
      try {
        _pwriteLoop(fh, _copyToNative(data, arena), data.length, offset);
      } finally {
        _native.smb2_close(_ctx, fh);
      }
    });
  }

  /// Write [data] to a file, creating or truncating it.
  ///
  /// Replaces the entire file content with [data].
  ///
  /// Throws [Smb2Exception] on failure.
  void writeFile(String path, Uint8List data) {
    _ensureConnected();
    using((arena) {
      final fh = _native.smb2_open(
        _ctx,
        _path(path, arena),
        _flags.wronly | _flags.creat | _flags.trunc,
      );
      if (fh == nullptr) {
        throw _makeError(_native, _ctx, 'Open for write failed');
      }
      try {
        _pwriteLoop(fh, _copyToNative(data, arena), data.length, 0);
      } finally {
        _native.smb2_close(_ctx, fh);
      }
    });
  }

  // ─── Write handles (open once, write many, close once) ─────────────────

  /// Open a file for writing and return a reusable handle.
  ///
  /// The file is created if it doesn't exist.
  /// Use [writeHandle] to write, then [closeHandle] when done.
  ///
  /// Throws [Smb2Exception] if the file cannot be opened.
  Smb2Handle openFileHandleWrite(String path) {
    _ensureConnected();
    return using((arena) {
      final fh = _native.smb2_open(
        _ctx,
        _path(path, arena),
        _flags.wronly | _flags.creat,
      );
      if (fh == nullptr) {
        throw _makeError(_native, _ctx, 'Open for write failed');
      }
      return Smb2Handle._(fh);
    });
  }

  /// Write [data] at [offset] to an open file handle.
  ///
  /// The handle must have been obtained from [openFileHandleWrite].
  void writeHandle(Smb2Handle handle, Uint8List data, {int offset = 0}) {
    _ensureConnected();
    using((arena) {
      _pwriteLoop(handle._fh, _copyToNative(data, arena), data.length, offset);
    });
  }

  /// Flush all buffered writes on a file handle to the server.
  ///
  /// Ensures all previously written data is persisted on the remote disk.
  /// The handle must have been obtained from [openFileHandleWrite].
  ///
  /// Throws [Smb2Exception] on failure.
  void fsync(Smb2Handle handle) {
    _ensureConnected();
    if (_native.smb2_fsync(_ctx, handle._fh) < 0) {
      throw _makeError(_native, _ctx, 'Fsync failed');
    }
  }

  /// Truncate an open file handle to [length] bytes.
  ///
  /// [length] must be non-negative.
  /// Throws [Smb2Exception] on failure.
  void ftruncate(Smb2Handle handle, int length) {
    _ensureConnected();
    if (length < 0) throw _negativeLength();
    if (_native.smb2_ftruncate(_ctx, handle._fh, length) < 0) {
      throw _makeError(_native, _ctx, 'Ftruncate failed');
    }
  }

  // ─── Streaming write ────────────────────────────────────────────────────

  /// Write data from [chunks] to a file without loading everything into RAM.
  ///
  /// Creates or truncates the file, then writes each chunk sequentially.
  /// Uses a write handle internally — opens once, writes sequentially, closes.
  void writeFileChunked(String path, Iterable<Uint8List> chunks) {
    final handle = openFileHandleWrite(path);
    try {
      ftruncate(handle, 0);
      int offset = 0;
      for (final chunk in chunks) {
        writeHandle(handle, chunk, offset: offset);
        offset += chunk.length;
      }
    } finally {
      closeHandle(handle);
    }
  }

  // ─── File/directory management ─────────────────────────────────────────

  /// Delete a file.
  ///
  /// Throws [Smb2Exception] if the file cannot be deleted.
  void deleteFile(String path) {
    _ensureConnected();
    using((arena) {
      if (_native.smb2_unlink(_ctx, _path(path, arena)) < 0) {
        throw _makeError(_native, _ctx, 'Delete failed');
      }
    });
  }

  /// Create a directory.
  ///
  /// Throws [Smb2Exception] if the directory cannot be created.
  void mkdir(String path) {
    _ensureConnected();
    using((arena) {
      if (_native.smb2_mkdir(_ctx, _path(path, arena)) < 0) {
        throw _makeError(_native, _ctx, 'Mkdir failed');
      }
    });
  }

  /// Delete an empty directory.
  ///
  /// Throws [Smb2Exception] if the directory cannot be removed.
  void rmdir(String path) {
    _ensureConnected();
    using((arena) {
      if (_native.smb2_rmdir(_ctx, _path(path, arena)) < 0) {
        throw _makeError(_native, _ctx, 'Rmdir failed');
      }
    });
  }

  /// Rename or move a file or directory.
  ///
  /// Both paths are validated for embedded NUL bytes.
  /// Throws [Smb2Exception] on failure.
  void rename(String oldPath, String newPath) {
    _ensureConnected();
    using((arena) {
      final rc = _native.smb2_rename(
        _ctx,
        _path(oldPath, arena),
        _path(newPath, arena),
      );
      if (rc < 0) throw _makeError(_native, _ctx, 'Rename failed');
    });
  }

  /// Truncate a file to [length] bytes.
  ///
  /// [length] must be non-negative.
  /// Throws [Smb2Exception] on failure.
  void truncate(String path, int length) {
    _ensureConnected();
    if (length < 0) throw _negativeLength();
    using((arena) {
      if (_native.smb2_truncate(_ctx, _path(path, arena), length) < 0) {
        throw _makeError(_native, _ctx, 'Truncate failed');
      }
    });
  }

  /// Set the last-modified and/or last-accessed time of a file or directory.
  ///
  /// Fields left `null` are not changed on the server. At least one of
  /// [modified] / [accessed] must be provided. Timestamps are sent with
  /// microsecond precision; must be after the Unix epoch (SMB encodes
  /// "leave unchanged" as 0, so the epoch itself is not representable).
  ///
  /// Call this *after* the write handle on [path] is closed — servers
  /// refresh the modified time on write/close, which would overwrite an
  /// earlier set.
  ///
  /// Throws [Smb2Exception] on failure.
  void setFileTimes(String path, {DateTime? modified, DateTime? accessed}) {
    _ensureConnected();
    final mtimeUs = modified?.microsecondsSinceEpoch ?? 0;
    final atimeUs = accessed?.microsecondsSinceEpoch ?? 0;
    if (modified == null && accessed == null) {
      throw const Smb2Exception(
        'setFileTimes needs at least one of modified/accessed',
        22,
        Smb2ErrorType.invalidParam,
      );
    }
    if (mtimeUs < 0 || atimeUs < 0 || (modified != null && mtimeUs == 0) ||
        (accessed != null && atimeUs == 0)) {
      throw const Smb2Exception(
        'setFileTimes timestamps must be after the Unix epoch',
        22,
        Smb2ErrorType.invalidParam,
      );
    }
    using((arena) {
      final rc =
          _native.smb2_utimes(_ctx, _path(path, arena), atimeUs, mtimeUs);
      if (rc < 0) throw _makeError(_native, _ctx, 'Set file times failed');
    });
  }

  // ─── Helpers ────────────────────────────────────────────────────────────

  void _ensureConnected() {
    if (_ctx == nullptr) {
      throw const Smb2Exception('Not connected. Call connect() first.');
    }
  }

  /// NUL-rejecting path allocation against [arena].
  ///
  /// libsmb2 takes a C `const char *`, so an embedded NUL silently
  /// truncates the path on the wire — a caller that builds a path from
  /// untrusted input could let a prefix short-circuit the suffix.
  Pointer<Char> _path(String path, Arena arena) {
    if (path.contains('\u0000')) {
      throw const Smb2Exception(
        'Invalid path: contains NUL byte',
        22,
        Smb2ErrorType.invalidParam,
      );
    }
    return path.toNativeUtf8(allocator: arena).cast();
  }

  /// Copy [data] into a buffer owned by [arena] (freed on scope exit).
  Pointer<Uint8> _copyToNative(Uint8List data, Arena arena) {
    final buf = arena<Uint8>(data.length);
    buf.asTypedList(data.length).setAll(0, data);
    return buf;
  }

  /// Send [length] bytes from [buf] to handle [fh] starting at [offset],
  /// chunking by the server-negotiated `max_write_size`.
  void _pwriteLoop(
    Pointer<smb2fh> fh,
    Pointer<Uint8> buf,
    int length,
    int offset,
  ) {
    final maxChunk = _native.smb2_get_max_write_size(_ctx);
    final chunkSize = maxChunk == 0 ? _writeChunkFallback : maxChunk;

    var total = 0;
    while (total < length) {
      final remaining = length - total;
      final toWrite = remaining < chunkSize ? remaining : chunkSize;
      final n =
          _native.smb2_pwrite(_ctx, fh, buf + total, toWrite, offset + total);
      if (n < 0) throw _makeError(_native, _ctx, 'Write failed');
      if (n == 0) break; // cannot make progress
      total += n;
    }
  }
}

/// POSIX-style open flags as understood by `smb2_open` in libsmb2.
///
/// libsmb2 forwards the integer straight to the host OS's `<fcntl.h>`
/// interpretation, and the prebuilt per-platform binary was compiled
/// against that platform's `<fcntl.h>`. So the Dart side must use the
/// *host* OS's values, not a single "portable" set.
///
/// Values audited from:
///   * Linux/Android (glibc/bionic): O_CREAT=0o100, O_EXCL=0o200,
///     O_TRUNC=0o1000, O_APPEND=0o2000.
///   * macOS/iOS (Apple libc): O_APPEND=0x8, O_CREAT=0x200, O_TRUNC=0x400,
///     O_EXCL=0x800.
///   * Windows (mingw-w64 / MSVCRT): O_APPEND=0x8, O_CREAT=0x100,
///     O_TRUNC=0x200, O_EXCL=0x400.
///
/// O_RDONLY/O_WRONLY/O_RDWR are 0/1/2 on every supported platform.
class _OpenFlags {
  final int rdonly;
  final int wronly;
  final int rdwr;
  final int creat;
  final int trunc;
  final int excl;
  final int append;

  const _OpenFlags({
    required this.rdonly,
    required this.wronly,
    required this.rdwr,
    required this.creat,
    required this.trunc,
    required this.excl,
    required this.append,
  });

  static const _linuxLike = _OpenFlags(
    rdonly: 0,
    wronly: 1,
    rdwr: 2,
    creat: 0x40,
    trunc: 0x200,
    excl: 0x80,
    append: 0x400,
  );

  static const _darwin = _OpenFlags(
    rdonly: 0,
    wronly: 1,
    rdwr: 2,
    creat: 0x200,
    trunc: 0x400,
    excl: 0x800,
    append: 0x8,
  );

  static const _windows = _OpenFlags(
    rdonly: 0,
    wronly: 1,
    rdwr: 2,
    creat: 0x100,
    trunc: 0x200,
    excl: 0x400,
    append: 0x8,
  );

  static _OpenFlags _resolve() {
    if (Platform.isLinux || Platform.isAndroid) return _linuxLike;
    if (Platform.isMacOS || Platform.isIOS) return _darwin;
    if (Platform.isWindows) return _windows;
    throw UnsupportedError(
      'dart_smb2: unsupported platform ${Platform.operatingSystem}',
    );
  }
}

final _OpenFlags _flags = _OpenFlags._resolve();

/// Maximum length for a symlink target. 4096 matches Linux PATH_MAX, a
/// sane upper bound for any real share.
const int _readlinkBufferSize = 4096;

/// Fallback chunk size used when libsmb2 reports `max_write_size` of 0.
const int _writeChunkFallback = 1024 * 1024;

Smb2Exception _negativeLength() => const Smb2Exception(
      'Truncate length must be non-negative',
      22,
      Smb2ErrorType.invalidParam,
    );

/// Build a typed [Smb2Exception] from the current libsmb2 context error.
///
/// Both signals (message + errno) are consulted because libsmb2's
/// `smb2_set_error` is sometimes invoked without updating the NT-status
/// field — message-based classification picks up those transport-failure
/// paths even when the errno is stale (see [Smb2ErrorType.classify]).
Smb2Exception _makeError(
  LibSmb2Bindings lib,
  Pointer<smb2_context> ctx,
  String prefix,
) {
  final ptr = lib.smb2_get_error(ctx);
  final msg =
      ptr == nullptr ? 'Unknown error' : ptr.cast<Utf8>().toDartString();
  final nt = lib.smb2_get_nterror(ctx);
  final errno = lib.nterror_to_errno(nt);
  return Smb2Exception(
    '$prefix: $msg',
    errno,
    Smb2ErrorType.classify(msg, errno),
  );
}

Smb2FileType _parseType(int type) => switch (type) {
      SMB2_TYPE_DIRECTORY => Smb2FileType.directory,
      SMB2_TYPE_LINK => Smb2FileType.link,
      _ => Smb2FileType.file, // SMB2_TYPE_FILE (0) and any unexpected value.
    };

DateTime _toUtc(int seconds) =>
    DateTime.fromMillisecondsSinceEpoch(seconds * 1000, isUtc: true);

Smb2Stat _statFromNative(smb2_stat_64 st) => Smb2Stat(
      type: _parseType(st.smb2_type),
      size: st.smb2_size,
      modified: _toUtc(st.smb2_mtime),
      created: _toUtc(st.smb2_btime),
    );

/// Apply optional credentials + timeout to a freshly-created context before
/// connecting. Centralised so the connect and share-enum paths can't drift
/// on which setters are called and in what order.
void _applyCredentials(
  LibSmb2Bindings lib,
  Pointer<smb2_context> ctx, {
  String? user,
  String? password,
  String? domain,
  int timeoutSeconds = 0,
}) {
  using((arena) {
    if (user != null && user.isNotEmpty) {
      lib.smb2_set_user(ctx, user.toNativeUtf8(allocator: arena).cast());
    }
    // Immuch360: an empty password is a real credential (a Freebox Server logs "freebox" on with an empty password);
    // only a null password means an anonymous logon
    if (password != null) {
      lib.smb2_set_password(
        ctx,
        password.toNativeUtf8(allocator: arena).cast(),
      );
    }
    if (domain != null && domain.isNotEmpty) {
      lib.smb2_set_domain(ctx, domain.toNativeUtf8(allocator: arena).cast());
    }
  });
  if (timeoutSeconds > 0) lib.smb2_set_timeout(ctx, timeoutSeconds);
}
